name: Automatic Release

on:
  push:
    tags:
      - 'v*.*.*' # Detecta tags con el formato semántico, como v1.0.0

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3


    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        RELEASE_NAME="Release $VERSION"

        # Crea el release automáticamente
        gh release create $VERSION --title "$RELEASE_NAME" --notes "Automated release for version $VERSION."
